services:
  - type: web
    name: floorplan-analyzer-api
    runtime: python
    envVars:
      - key: PORT
        value: 10000
    buildCommand: |
      apt-get update && apt-get install -y \
        libgl1-mesa-dev \
        libglib2.0-0 \
        poppler-utils
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon